# Generated by Django 5.2.6 on 2026-05-18 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cita', '📅 Cita'), ('pedido', '📦 Pedido'), ('stock', '🚨 Inventario'), ('sistema', 'ℹ️ Sistema')], default='sistema', max_length=10, verbose_name='Tipo de notificación')),
                ('mensaje', models.TextField(help_text='Texto de la notificación visible por el usuario.', verbose_name='Mensaje')),
                ('url', models.CharField(blank=True, default='', help_text='Enlace interno al que lleva al hacer clic. Dejar vacío si no aplica.', max_length=255, verbose_name='URL de destino')),
                ('leido', models.BooleanField(db_index=True, default=False, verbose_name='Leído')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario destino')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones_notificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
