# Generated by Django 5.2.6 on 2026-05-18 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leido', '-fecha_creacion'], name='notif_user_leido_date'),
        ),
    ]
