# Generated by Django 5.2.6 on 2026-05-19 20:55

import servicios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto representativa del servicio. Opcional.', null=True, upload_to=servicios.models.servicio_imagen_upload_path, verbose_name='Imagen del servicio'),
        ),
    ]
