# Generated by Django 5.2.6 on 2026-05-18 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_evidencia_obligatoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={'ordering': ['pk'], 'verbose_name': 'Item del pedido', 'verbose_name_plural': 'Items del pedido'},
        ),
    ]
