# Generated by Django 5.2.6 on 2026-06-08 23:14

import entregas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0004_alter_pedidoitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='firma_imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la firma del cliente. Obligatorio al marcar como Entregado. Máximo 5MB.', null=True, upload_to=entregas.models.firma_upload_path, verbose_name='Firma del cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='foto_evidencia',
            field=models.ImageField(blank=True, help_text='Foto del paquete entregado. Obligatorio al marcar como Entregado. Máximo 5MB.', null=True, upload_to=entregas.models.evidencia_upload_path, verbose_name='Foto de evidencia'),
        ),
    ]
