# Generated by Django 5.2.6 on 2026-05-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_reclassify_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('vacunas', 'Vacunas'), ('medicamentos', 'Medicamentos'), ('alimentos', 'Alimentos'), ('insumos', 'Insumos médicos'), ('higiene', 'Higiene y cuidado'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría'),
        ),
    ]
